### PR TITLE
Tickets/dm 37682

### PR DESCRIPTION
**Pull request by edennihy**

### CODE REVIEW

**Review by patrickingraham — APPROVED** [review]
All good.

**Comment by edennihy** [comment]
Squashed commits to remove "Empty commit" from history.

**Comment by tribeiro** [comment]
Please! update the version history before merging. You will also want to wait for #81 to be merged and rebase before doing anything else.

**Comment by edennihy** [comment]
Version history update and changes from PR#81 captured in the rebase.

**Pull request merged**
