### PR TITLE
DM-36813: OCPS calibs script: remove RuntimeErrors in script

### PR DESCRIPTION
**Pull request by plazas**

### CODE REVIEW

**Review by tribeiro — COMMENTED** [review]
I think you can also remove the [exception in line 498](https://github.com/lsst-ts/ts_externalscripts/blob/1b72954cbf824c0216310ee53f7cba8b7f92c900/python/lsst/ts/externalscripts/base_make_calibrations.py#L498-L503). Again, the script should only fail if it fails to take data. I think what you should do here is log and error, e.g.;

```
self.log.error(
                "Timeout waiting for images to ingest in the OODS, "
                f"expected: {self.number_of_images_expected}, "
                f"received: {len(self.image_in_oods_samples[image_type])}. "
                f"Missing image ids: {missing_image_ids}"
)
``` 

and keep going, even sending the job to the OCPS to process... the alarm will have to capture the process failure later...

I also found a couple more RuntimeErrors that can be converted to warning or error log messages:

https://github.com/lsst-ts/ts_externalscripts/blob/1b72954cbf824c0216310ee53f7cba8b7f92c900/python/lsst/ts/externalscripts/base_make_calibrations.py#L696-L699

https://github.com/lsst-ts/ts_externalscripts/blob/1b72954cbf824c0216310ee53f7cba8b7f92c900/python/lsst/ts/externalscripts/base_make_calibrations.py#L916-L919

https://github.com/lsst-ts/ts_externalscripts/blob/1b72954cbf824c0216310ee53f7cba8b7f92c900/python/lsst/ts/externalscripts/base_make_calibrations.py#L1025-L1027

[This one](https://github.com/lsst-ts/ts_externalscripts/blob/1b72954cbf824c0216310ee53f7cba8b7f92c900/python/lsst/ts/externalscripts/base_make_calibrations.py#L1480-L1483) I am a bit on the fence. It seems like something the configuration should capture, but I see why you would want to put this here, so I am ok leaving it...

**Comment by tribeiro** [comment]
By the way, I think [this one](https://github.com/lsst-ts/ts_externalscripts/blob/1b72954cbf824c0216310ee53f7cba8b7f92c900/python/lsst/ts/externalscripts/base_make_calibrations.py#L362-L366) is ok to keep.

**Comment by tribeiro** [comment]
@plazas Any updates here?

**Comment by plazas** [comment]
> @plazas Any updates here?

Thanks for the reminder. I made the changes.

**Review by tribeiro — APPROVED** [review]
Looks good! thanks for the updates!

**Pull request merged**
